REPO = 'gitolite@54.213.194.67:puppet.git'
SSH = 'ssh -i ~/.ssh/ConsensusNOC.pem  -l root'

#######################
# run puppet apply
#######################
desc "Run Puppet on ENV['CLIENT']"
task :apply do
  client = ENV['CLIENT']
  sh "git push"
  sh "#{SSH} #{client} pull-updates"
end

#######################
# BootStrap a New Server
#######################
desc "Bootstrap Puppet on ENV['CLIENT'] with
  hostname ENV['HOSTNAME']"
task :bootstrap do
  client = ENV['CLIENT']
  hostname = ENV['HOSTNAME'] || client
  commands = <<BOOTSTRAP
sudo hostname #{hostname} && \
sudo su - c 'echo #{hostname} >/etc/hostname' && \
rpm -ivh https://yum.puppetlabs.com/el/6/products/x86_64/puppetlabs-release-6-7.noarch.rpm
yum update && yum -y install puppet
git clone #{REPO} puppet && \
sudo puppet apply --modulepath=/etc/puppet/modules /etc/puppet/manifests/site.pp
BOOTSTRAP
  sh "#{SSH} #{client} '#{commands}'"
end

#######################
# check syntax
#######################
desc "Add syntax check hook to your git repo"
task :add_check do
  here = File.dirname(__FILE__)
  sh "ln -s #{here}/hooks/check_syntax.sh
    #{here}/.git/hooks/pre-commit"
  puts "Puppet syntax check hook added"
end
